// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwETzglXMSGex2CHBdNRJSIt0Rpg9DOmc',
    appId: '1:939936870034:web:9c5e180e373340cd06404b',
    messagingSenderId: '939936870034',
    projectId: 'dog-app-ec6ec',
    authDomain: 'dog-app-ec6ec.firebaseapp.com',
    storageBucket: 'dog-app-ec6ec.appspot.com',
    measurementId: 'G-V0X7LX50SS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvzvP7uI6OGKc4S0IaB_2Q33od-kn2bdw',
    appId: '1:939936870034:android:12d68ae563cd231d06404b',
    messagingSenderId: '939936870034',
    projectId: 'dog-app-ec6ec',
    storageBucket: 'dog-app-ec6ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDUhi9XYnfCx_QcJKDPFN1_kwinn4CgGg',
    appId: '1:939936870034:ios:519c00a9fb521fed06404b',
    messagingSenderId: '939936870034',
    projectId: 'dog-app-ec6ec',
    storageBucket: 'dog-app-ec6ec.appspot.com',
    iosClientId: '939936870034-74uodc85aalapfd5qq7v0fapgs5u3t1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.dogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDUhi9XYnfCx_QcJKDPFN1_kwinn4CgGg',
    appId: '1:939936870034:ios:519c00a9fb521fed06404b',
    messagingSenderId: '939936870034',
    projectId: 'dog-app-ec6ec',
    storageBucket: 'dog-app-ec6ec.appspot.com',
    iosClientId: '939936870034-74uodc85aalapfd5qq7v0fapgs5u3t1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.dogApp',
  );
}
